### ISSUE TITLE
Half rendered scene

### ISSUE THREAD

**Issue by rametoyer** [OSU-Infovis/BlocksAndGuides#4]
We have to click a diagram twice to render it fully.  this is probably related to the timeouts.  We need to refactor all of these timeouts out of the code  (as discussed earlier).

**Comment by nels-o** [comment]
This is addressed in 655dbc7a64efeead9fa05f0c9592daa160d62fc3 

It appears to work correctly in FF, Chrome, and IE.

(couldn't resist)

**Comment by rametoyer** [comment]
I forgot to close this previously...it should have been fixed in the last version I pushed.
